# This is a basic workflow to help you get started with Actions

name: Lab1

# Controls when the workflow will run
on: [push, create]
  # Triggers the workflow on push or pull request events but only for the main branch
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: echo "id cr.yandex/crp2dg4s9q5he94070t8 let's go"
      - run: sudo docker build . -t cr.yandex/crp2dg4s9q5he94070t8/Lab1-Cloud


